name: Formatting Checks

on:
  push:
    branches: ["main", "add_features"]
  pull_request:

jobs:
  black:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Black
        run: python -m pip install --upgrade pip black
      - name: Run Black in check mode
        run: black --check src

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    if: ${{ hashFiles('**/Cargo.toml') != '' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
