name: Formatting Checks

on:
  push:
    branches: ["main", "add_features"]
  pull_request:

jobs:
  black:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Black
        run: python -m pip install --upgrade pip black
      - name: Run Black in check mode
        run: black --check src

  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Ruff
        run: python -m pip install --upgrade pip ruff
      - name: Run Ruff check
        run: ruff check src tests
